version: "3.9"

services:
  endee:
    image: endeeai/endee:latest
    container_name: endee
    ports:
      - "8080:8080"
    environment:
      - ENDPOINT_KEY=secret_key_here
    restart: unless-stopped

  streamlit:
    build: .
    container_name: finance_app
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      - endee
