version: '3.8'

services:
  endee:
    image: endeeio/endee-server:latest
    container_name: endee
    ports:
      - "8080:8080"

  streamlit:
    build: .
    container_name: finance-app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    depends_on:
      - endee
